// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0qKuHAV6BGDMUqDbPyZMYCE5bWe_VZ4A',
    appId: '1:939067951370:web:941715e25bc9641ccb12f3',
    messagingSenderId: '939067951370',
    projectId: 'flutter-stayco',
    authDomain: 'flutter-stayco.firebaseapp.com',
    storageBucket: 'flutter-stayco.appspot.com', 
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLb0yYW0u0-bAdF-oUoGyj7QIs_D0EsIE',
    appId: '1:939067951370:android:17289e1fd29b3797cb12f3',
    messagingSenderId: '939067951370',
    projectId: 'flutter-stayco',
    storageBucket: 'flutter-stayco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGLm_80Pf4LuMSdO2KO9DOBGJWlBWBBk',
    appId: '1:939067951370:ios:4d962a73562e9ffacb12f3',
    messagingSenderId: '939067951370',
    projectId: 'flutter-stayco',
    storageBucket: 'flutter-stayco.firebasestorage.app',
    iosBundleId: 'com.example.utpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0qKuHAV6BGDMUqDbPyZMYCE5bWe_VZ4A',
    appId: '1:939067951370:web:e56f05a0cae1fd8dcb12f3',
    messagingSenderId: '939067951370',
    projectId: 'flutter-stayco',
    authDomain: 'flutter-stayco.firebaseapp.com',
    storageBucket: 'flutter-stayco.firebasestorage.app',
  );
}
